### ISSUE TITLE
`{replace, delete}_on` methods

### ISSUE THREAD

**Issue by CraftSpider** [CraftSpider/jsonpath-plus#3]
Possible API enhancement, replace or delete matched paths in-place instead of by cloning and returning the new value.

**Comment by stefanpieck** [comment]
For my use case I would need a way to decide in the callback of the replace whether to replace a value or to delete the value.
My first Idea would be something like 
```
pub fn replace<F>(value: Value, path: &str, fun: &mut F) -> Value
where
    F: (Value) -> Option<Value>,
```
Where an None as result of the callback would lead to a deletion.

Maybe this can match into your Ideas here.

**Comment by CraftSpider** [comment]
I'll add a set of methods like that, most likely as `try_replace` and `try_replace_on` or similar.

**Comment by CraftSpider** [comment]
Added `replace_on` and `delete_on` in `0.1.2`, and `try_replace`/`try_replace_on` in `0.1.3`
